In [ ]:
# Policy Gradient

# https://github.com/seungeunrho/minimalRL/blob/master/REINFORCE.py
# Ref: https://www.youtube.com/watch?v=y8UPGr36ccI (11分開始有說明loss)

In [1]:
import gym
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.distributions import Categorical

#Hyperparameters
learning_rate = 0.0002
gamma         = 0.98

class Policy(nn.Module):
    def __init__(self):
        super(Policy, self).__init__()
        self.data = []
        
        self.fc1 = nn.Linear(4, 128)
        self.fc2 = nn.Linear(128, 2)
        self.optimizer = optim.Adam(self.parameters(), lr=learning_rate)
        
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.softmax(self.fc2(x), dim=0)
        return x
      
    def put_data(self, item):
        self.data.append(item)
        
    def train_net(self):
        R = 0
        # data是玩完一個episode蒐集起來的(r, a)pair
        for r, log_prob in self.data[::-1]:
            R = r + gamma * R  # 除了看instant r，也要考慮未來的期望衰減reward R，越前面的r越會考慮未來R
            # 這裡就等於max(log_prob) --> cross entropy，min -summation(y_hat * log(y_i)) --> 因為y_hat大部分都是0 --> = max(log(y_i))
            loss = -log_prob * R  # 這邊就像train一個分類問題，把s跟a對起來訓練，然後給予R的權重，Reward越大代表這個a答案越好，權重越大
            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()  # 每一步都更新一次
        self.data = []

def main():
    env = gym.make('CartPole-v1')
    pi = Policy()
    score = 0.0
    print_interval = 20
    
    for n_epi in range(10000):
        s = env.reset()
        for t in range(501): # CartPole-v1 forced to terminates at 500 step.
            # print(s)  # [-0.05109565  0.01887992  0.10848381  0.265779  ]
            prob = pi(torch.from_numpy(s).float())  # [0.45, 0.55]
            m = Categorical(prob)  # choose action based on the prob
            a = m.sample()
            s_prime, r, done, info = env.step(a.item())
            pi.put_data((r,torch.log(prob[a])))
            
            s = s_prime
            score += r
            if done:
                break

        pi.train_net()
        
        if n_epi % print_interval==0 and n_epi!=0:
            print("# of episode :{}, avg score : {}".format(n_epi, score/print_interval))
            score = 0.0
    env.close()
    
if __name__ == '__main__':
    main()

[-0.01778966 -0.02186928 -0.03338169 -0.01818751]
[-0.01822705 -0.216497   -0.03374544  0.26377902]
[-0.02255699 -0.02091004 -0.02846986 -0.03935367]
[-0.02297519  0.17460836 -0.02925693 -0.34088142]
[-0.01948302 -0.02008537 -0.03607456 -0.05756612]
[-0.01988473 -0.214672   -0.03722588  0.22352031]
[-0.02417817 -0.01903831 -0.03275547 -0.0806688 ]
[-0.02455894 -0.21367577 -0.03436885  0.20150239]
[-0.02883245 -0.40828976 -0.0303388   0.48314852]
[-0.03699825 -0.60297068 -0.02067583  0.76611727]
[-0.04905766 -0.40757024 -0.00535349  0.467001  ]
[-0.05720906 -0.60261614  0.00398653  0.75799175]
[-0.06926139 -0.40754936  0.01914637  0.46656593]
[-0.07741237 -0.21270308  0.02847769  0.17997878]
[-0.08166644 -0.01799997  0.03207726 -0.10358616]
[-0.08202644  0.17664794  0.03000554 -0.38597873]
[-0.07849348  0.37133137  0.02228597 -0.66905212]
[-0.07106685  0.56613647  0.00890492 -0.95463567]
[-0.05974412  0.7611375  -0.01018779 -1.24450761]
[-0.04452137  0.56614773 -0.03507794 -0.9550333 ]


[ 0.55632864  2.06562827 -0.13938316 -1.77095184]
[ 0.5976412   2.26202091 -0.1748022  -2.10352994]
[-0.02904868  0.03069599  0.04746917  0.00366194]
[-0.02843476 -0.16507346  0.04754241  0.31093603]
[-0.03173623 -0.36083938  0.05376113  0.6182253 ]
[-0.03895302 -0.55666945  0.06612563  0.92734417]
[-0.0500864  -0.36249967  0.08467252  0.65615281]
[-0.0573364  -0.16865217  0.09779557  0.39128726]
[-0.06070944  0.0249557   0.10562132  0.13096918]
[-0.06021033  0.21841856  0.1082407  -0.12661296]
[-0.05584196  0.02192585  0.10570844  0.19816185]
[-0.05540344  0.21538951  0.10967168 -0.05939334]
[-0.05109565  0.01887992  0.10848381  0.265779  ]
[-0.05071805  0.21229978  0.11379939  0.00918648]
[-0.04647205  0.01574529  0.11398312  0.33549604]
[-0.04615715 -0.18079869  0.12069304  0.66183747]
[-0.04977312  0.01245557  0.13392979  0.40946251]
[-0.04952401  0.20544971  0.14211904  0.1618215 ]
[-0.04541502  0.00860947  0.14535547  0.49574755]
[-0.04524283  0.2014148   0.15527042  0.25217359]


[-0.07885978 -0.18760084  0.0317372   0.26847341]
[-0.08261179 -0.38316101  0.03710667  0.57099511]
[-0.09027501 -0.18857853  0.04852657  0.29022916]
[-0.09404659  0.00581909  0.05433116  0.01323721]
[-0.0939302   0.20012147  0.0545959  -0.26182079]
[-0.08992777  0.39442331  0.04935949 -0.53679606]
[-0.08203931  0.58881776  0.03862356 -0.81352681]
[-0.07026295  0.39318872  0.02235303 -0.50894959]
[-0.06239918  0.19775909  0.01217404 -0.20930714]
[-0.058444    0.0024652   0.00798789  0.08719107]
[-0.05839469 -0.19277033  0.00973172  0.38238344]
[-0.0622501   0.0022121   0.01737938  0.09278472]
[-0.06220586 -0.19315458  0.01923508  0.39089978]
[-0.06606895 -0.38854417  0.02705307  0.6895847 ]
[-0.07383983 -0.19380789  0.04084477  0.4055398 ]
[-0.07771599  0.00071176  0.04895556  0.1260087 ]
[-0.07770175 -0.1950761   0.05147574  0.43372582]
[-0.08160328 -0.39088761  0.06015025  0.74218122]
[-0.08942103 -0.19664528  0.07499388  0.46901816]
[-0.09335393 -0.3927421   0.08437424  0.78436417]


[ 0.01514007  0.0120294  -0.04696142 -0.04455468]
[ 0.01538066  0.2077922  -0.04785251 -0.35167672]
[ 0.0195365   0.01338226 -0.05488605 -0.07445889]
[ 0.01980415 -0.18091164 -0.05637522  0.20041469]
[ 0.01618591  0.01496939 -0.05236693 -0.10950561]
[ 0.0164853  -0.17936457 -0.05455704  0.16620689]
[ 0.01289801  0.01649418 -0.05123291 -0.14317593]
[ 0.01322789  0.212311   -0.05409642 -0.45157164]
[ 0.01747411  0.40815461 -0.06312786 -0.76080391]
[ 0.02563721  0.60408682 -0.07834393 -1.07266408]
[ 0.03771894  0.41008294 -0.09979722 -0.80556043]
[ 0.0459206   0.2164603  -0.11590842 -0.54586326]
[ 0.05024981  0.41300373 -0.12682569 -0.87270106]
[ 0.05850988  0.21981338 -0.14427971 -0.62242985]
[ 0.06290615  0.41662387 -0.15672831 -0.95684944]
[ 0.07123863  0.61346658 -0.1758653  -1.29438423]
[ 0.08350796  0.4209603  -0.20175298 -1.06151707]
[ 0.0162365  -0.02013043  0.00443618  0.0289072 ]
[ 0.01583389  0.17492762  0.00501433 -0.26237277]
[ 0.01933244 -0.02026555 -0.00023313  0.03188751]


[ 0.01167288  0.3396481   0.04335646 -0.41978696]
[ 0.01846585  0.14393949  0.03496073 -0.11375711]
[ 0.02134463  0.33854351  0.03268558 -0.3952084 ]
[ 0.02811551  0.5331868   0.02478141 -0.67740954]
[ 0.03877924  0.33772947  0.01123322 -0.37702858]
[ 0.04553383  0.14244979  0.00369265 -0.08082504]
[ 0.04838283 -0.0527249   0.00207615  0.21302064]
[ 0.04732833 -0.24787647  0.00633656  0.50635775]
[ 0.0423708  -0.05284438  0.01646372  0.21567843]
[ 0.04131391 -0.24819778  0.02077729  0.51350893]
[ 0.03634996 -0.44360611  0.03104747  0.81266624]
[ 0.02747783 -0.63913925  0.04730079  1.11495109]
[ 0.01469505 -0.83484919  0.06959981  1.42208891]
[-0.00200194 -0.6406537   0.09804159  1.15194674]
[-0.01481501 -0.8369084   0.12108053  1.47369318]
[-0.03155318 -0.64345659  0.15055439  1.22115069]
[-0.04442231 -0.45056064  0.1749774   0.97917576]
[-0.05343352 -0.64754147  0.19456092  1.32131655]
[ 0.02915209 -0.04721381  0.03858614 -0.04665125]
[ 0.02820781 -0.24286721  0.03765311  0.25795191]


[-0.0386562  -0.04491433  0.03224093  0.02025464]
[-0.03955448  0.14973077  0.03264602 -0.26208409]
[-0.03655987  0.34437188  0.02740434 -0.54429396]
[-0.02967243  0.14887577  0.01651846 -0.24310403]
[-0.02669491  0.34375792  0.01165638 -0.53053117]
[-0.01981976  0.14847396  0.00104575 -0.23419823]
[-0.01685028 -0.04666292 -0.00363821  0.05881437]
[-0.01778353  0.14851101 -0.00246192 -0.23501421]
[-0.01481331 -0.04657568 -0.00716221  0.05689113]
[-0.01574483 -0.24159421 -0.00602439  0.34730575]
[-0.02057671 -0.43662995  0.00092173  0.6380829 ]
[-0.02930931 -0.24152087  0.01368339  0.34569039]
[-0.03413973 -0.04659621  0.0205972   0.05735356]
[-0.03507165  0.14822445  0.02174427 -0.2287603 ]
[-0.03210716 -0.04720138  0.01716906  0.07070146]
[-0.03305119  0.14767028  0.01858309 -0.21651548]
[-0.03009779  0.34252171  0.01425278 -0.50327905]
[-0.02324735  0.5374399   0.0041872  -0.79143648]
[-0.01249855  0.34226071 -0.01164153 -0.49743922]
[-0.00565334  0.14730483 -0.02159031 -0.20844774]


[0.13490376 0.2155537  0.04202727 0.2056132 ]
[0.13921484 0.01985674 0.04613954 0.51125183]
[ 0.13961197 -0.17588375  0.05636458  0.8181103 ]
[0.1360943  0.01842322 0.07272678 0.54367511]
[ 0.13646276 -0.17764136  0.08360028  0.85835739]
[0.13290993 0.01624831 0.10076743 0.59308847]
[ 0.1332349  -0.18012909  0.1126292   0.91573583]
[0.12963232 0.01330438 0.13094392 0.66046703]
[ 0.12989841 -0.18337319  0.14415326  0.99134537]
[0.12623094 0.00955632 0.16398017 0.74718715]
[ 0.12642207 -0.18740243  0.17892391  1.08665649]
[0.12267402 0.0049671  0.20065704 0.85503214]
[-0.01574971 -0.01882612  0.03927375  0.01761662]
[-0.01612623  0.17571124  0.03962608 -0.26242088]
[-0.012612   -0.01995328  0.03437767  0.04249253]
[-0.01301107 -0.21555091  0.03522752  0.34582065]
[-0.01732209 -0.41115579  0.04214393  0.64940068]
[-0.0255452  -0.21664546  0.05513194  0.3702809 ]
[-0.02987811 -0.02234838  0.06253756  0.09547867]
[-0.03032508  0.17182409  0.06444713 -0.17683661]
[-0.0268886  -0.02415812  0.

[ 0.08049174  0.37709575 -0.0750054  -0.59541509]
[ 0.08803366  0.18309925 -0.0869137  -0.32726941]
[ 0.09169564 -0.01068473 -0.09345909 -0.0632111 ]
[ 0.09148195 -0.20435108 -0.09472331  0.19858366]
[ 0.08739493 -0.00801093 -0.09075164 -0.12241334]
[ 0.08723471 -0.20172341 -0.09319991  0.14031529]
[ 0.08320024 -0.00539877 -0.0903936  -0.18025473]
[ 0.08309227 -0.19911875 -0.0939987   0.08259934]
[ 0.07910989 -0.00278383 -0.09234671 -0.23819785]
[ 0.07905421  0.19352774 -0.09711067 -0.55852186]
[ 0.08292477  0.38986909 -0.1082811  -0.88015197]
[ 0.09072215  0.19637162 -0.12588414 -0.62337811]
[ 0.09464958  0.00321121 -0.1383517  -0.37284247]
[ 0.09471381  0.19999954 -0.14580855 -0.70575016]
[ 0.0987138   0.39680849 -0.15992356 -1.04054698]
[ 0.10664997  0.20413047 -0.1807345  -0.80203532]
[ 0.11073258  0.01188613 -0.1967752  -0.57121289]
[ 0.1109703  -0.18001159 -0.20819946 -0.34640042]
[ 0.01978264 -0.01180723 -0.02381663 -0.04322435]
[ 0.0195465   0.183648   -0.02468111 -0.34332548]


[-0.06251253  0.15564083  0.15666677  0.11119484]
[-0.05939971  0.34821139  0.15889067 -0.12825149]
[-0.05243549  0.15121228  0.15632564  0.21004245]
[-0.04941124  0.34379377  0.16052649 -0.02953452]
[-0.04253537  0.14677742  0.1599358   0.30918289]
[-0.03959982  0.33930214  0.16611946  0.07090237]
[-0.03281377  0.14223646  0.1675375   0.41104644]
[-0.02996904 -0.05481509  0.17575843  0.75151114]
[-0.03106535  0.13750392  0.19078865  0.51888422]
[-0.02831527  0.32950021  0.20116634  0.29186763]
[-0.02172526  0.52127073  0.20700369  0.06875747]
[-0.01129985  0.71291663  0.20837884 -0.15214886]
[ 0.00295848  0.90454049  0.20533586 -0.37254574]
[ 0.02104929  1.09624415  0.19788495 -0.59411501]
[ 0.04297418  1.2881267   0.18600265 -0.81852261]
[ 0.06873671  1.48028223  0.1696322  -1.04741425]
[ 0.09834235  1.28336524  0.14868391 -0.70664529]
[ 0.12400966  1.47614875  0.13455101 -0.94907786]
[ 0.15353263  1.6692279   0.11556945 -1.19664018]
[ 0.18691719  1.86268001  0.09163664 -1.45098082]


[ 0.01682047 -0.02079344 -0.04969653 -0.01970115]
[ 0.0164046  -0.21516877 -0.05009055  0.2568971 ]
[ 0.01210122 -0.40954112 -0.04495261  0.53336947]
[ 0.0039104  -0.21381674 -0.03428522  0.22686787]
[-0.00036593 -0.01822201 -0.02974786 -0.07642968]
[-0.00073037  0.17731349 -0.03127645 -0.37834774]
[ 0.0028159  -0.01735064 -0.03884341 -0.09568813]
[ 0.00246888 -0.21189496 -0.04075717  0.18449114]
[-0.00176902 -0.40641077 -0.03706735  0.46404325]
[-0.00989723 -0.21078515 -0.02778648  0.15991108]
[-0.01411293 -0.01527664 -0.02458826 -0.14140665]
[-0.01441847 -0.21003796 -0.02741639  0.14341881]
[-0.01861923 -0.01453432 -0.02454802 -0.15778586]
[-0.01890991  0.18093033 -0.02770373 -0.45811089]
[-0.01529131  0.37643274 -0.03686595 -0.75939584]
[-0.00776265  0.57204275 -0.05205387 -1.06344761]
[ 0.0036782   0.76781369 -0.07332282 -1.3720032 ]
[ 0.01903448  0.57368123 -0.10076289 -1.10312453]
[ 0.0305081   0.38001857 -0.12282538 -0.84367819]
[ 0.03810847  0.18676762 -0.13969894 -0.59200551]


[-0.00534501 -0.35449059  0.01730599  0.62254629]
[-0.01243482 -0.15961451  0.02975691  0.33536365]
[-0.01562711  0.03507159  0.03646418  0.05221102]
[-0.01492568 -0.16055373  0.0375084   0.35617203]
[-0.01813676  0.03401542  0.04463185  0.07554847]
[-0.01745645  0.22847006  0.04614281 -0.20272562]
[-0.01288705  0.03271962  0.0420883   0.10414869]
[-0.01223265  0.22721393  0.04417128 -0.1749641 ]
[-0.00768837  0.03148856  0.04067199  0.13131972]
[-0.0070586   0.22600501  0.04329839 -0.1482594 ]
[-0.0025385   0.03029063  0.0403332   0.15776278]
[-0.00193269  0.22481261  0.04348846 -0.12192814]
[0.00256356 0.02909546 0.04104989 0.1841516 ]
[ 0.00314547  0.22360674  0.04473293 -0.09530426]
[0.00761761 0.02787315 0.04282684 0.21114953]
[ 0.00817507 -0.16783414  0.04704983  0.51702853]
[0.00481839 0.02659484 0.0573904  0.23953535]
[ 0.00535028 -0.169298    0.06218111  0.54975435]
[0.00196432 0.02489793 0.0731762  0.27729288]
[ 0.00246228 -0.17118756  0.07872205  0.59212858]
[-0.00096147  0.

[0.01912845 0.03568611 0.00670863 0.04167751]
[ 0.01984217 -0.1595314   0.00754218  0.3364695 ]
[0.01665154 0.03548241 0.01427157 0.04617449]
[ 0.01736119  0.23039684  0.01519506 -0.24197168]
[0.02196913 0.03506117 0.01035563 0.05546517]
[ 0.02267035  0.23003312  0.01146493 -0.23393257]
[ 0.02727102  0.4249894   0.00678628 -0.52297715]
[ 0.0357708   0.62001518 -0.00367327 -0.81351394]
[ 0.04817111  0.42494373 -0.01994354 -0.52198868]
[ 0.05666998  0.62034064 -0.03038332 -0.82088877]
[ 0.06907679  0.42564734 -0.04680109 -0.53791492]
[ 0.07758974  0.62139495 -0.05755939 -0.84496933]
[ 0.09001764  0.42710364 -0.07445878 -0.57092813]
[ 0.09855971  0.62318644 -0.08587734 -0.88610804]
[ 0.11102344  0.4293287  -0.1035995  -0.62160994]
[ 0.11961002  0.23579437 -0.1160317  -0.36326874]
[ 0.1243259   0.04249625 -0.12329707 -0.10930803]
[ 0.12517583 -0.15066297 -0.12548324  0.14207369]
[ 0.12216257  0.04601189 -0.12264176 -0.18741433]
[ 0.12308281  0.24265559 -0.12639005 -0.51613073]
[ 0.12793592

[-0.83614239 -0.15216824  0.08426182  0.3640571 ]
[-0.83918575 -0.34838034  0.09154296  0.6820747 ]
[-0.84615336 -0.1546409   0.10518445  0.41955841]
[-0.84924618  0.03884563  0.11357562  0.1617999 ]
[-0.84846926 -0.15770358  0.11681162  0.48804372]
[-0.85162333  0.03559329  0.12657249  0.23433888]
[-0.85091147 -0.16108848  0.13125927  0.5641145 ]
[-0.85413324  0.03197122  0.14254156  0.31549555]
[-0.85349381 -0.16486296  0.14885147  0.64951787]
[-0.85679107  0.02790645  0.16184183  0.40716211]
[-0.85623294 -0.16909589  0.16998507  0.74617808]
[-0.85961486 -0.36610456  0.18490863  1.08716723]
[-0.86693695 -0.17383798  0.20665198  0.85773758]
[0.02203908 0.01049712 0.00622625 0.02762958]
[ 0.02224902  0.20552923  0.00677884 -0.26308241]
[ 0.02635961  0.40055377  0.00151719 -0.55361953]
[ 0.03437068  0.20541054 -0.0095552  -0.26045898]
[ 0.03847889  0.01042629 -0.01476438  0.02919486]
[ 0.03868742  0.20575683 -0.01418048 -0.26810958]
[ 0.04280256  0.01084009 -0.01954267  0.02006721]
[ 0.

[-0.09525083  0.58565042  0.12991407 -0.52793797]
[-0.08353782  0.77872823  0.11935531 -0.7770267 ]
[-0.06796325  0.58218479  0.10381477 -0.44930178]
[-0.05631956  0.77569692  0.09482874 -0.70754044]
[-0.04080562  0.57939814  0.08067793 -0.38657731]
[-0.02921766  0.77328767  0.07294638 -0.65277203]
[-0.0137519   0.57722977  0.05989094 -0.33804005]
[-0.00220731  0.77145061  0.05313014 -0.61125156]
[ 0.0132217   0.5756279   0.04090511 -0.30231905]
[ 0.02473426  0.77014371  0.03485873 -0.58182595]
[ 0.04013714  0.96476035  0.02322221 -0.86332718]
[ 0.05943234  0.76933007  0.00595567 -0.56343409]
[ 0.07481894  0.57412506 -0.00531302 -0.26888081]
[ 0.08630145  0.37907933 -0.01069063  0.02212163]
[ 0.09388303  0.18411232 -0.0102482   0.31141246]
[ 0.09756528  0.37937876 -0.00401995  0.01551526]
[ 0.10515285  0.18431469 -0.00370965  0.30692714]
[0.10883915 0.37948931 0.0024289  0.01307659]
[ 0.11642893  0.57457634  0.00269043 -0.278839  ]
[ 0.12792046  0.37941611 -0.00288635  0.01469127]
[ 0.

[-0.14864446  0.02486241 -0.14169059 -0.8387812 ]
[-0.14814721  0.2216053  -0.15846622 -1.1724559 ]
[-0.14371511  0.02885771 -0.18191534 -0.93335138]
[-0.14313795 -0.16340581 -0.20058236 -0.70290353]
[ 0.04876712 -0.02374806  0.02402295 -0.02644943]
[ 0.04829216  0.17102129  0.02349397 -0.31145709]
[ 0.05171259  0.36580079  0.01726482 -0.59663912]
[ 0.0590286   0.17044154  0.00533204 -0.29856831]
[ 0.06243743  0.36548708 -0.00063933 -0.58956485]
[ 0.06974718  0.17037409 -0.01243062 -0.29708338]
[ 0.07315466 -0.02456848 -0.01837229 -0.00834664]
[ 0.07266329 -0.21942219 -0.01853922  0.27848346]
[ 0.06827484 -0.41427482 -0.01296955  0.56526196]
[ 0.05998935 -0.60921244 -0.00166431  0.85383085]
[ 0.0478051  -0.41406784  0.0154123   0.56062505]
[ 0.03952374 -0.60940267  0.0266248   0.85812354]
[ 0.02733569 -0.41465335  0.04378727  0.57392986]
[ 0.01904262 -0.22017177  0.05526587  0.29535645]
[ 0.01463919 -0.41603627  0.061173    0.60494454]
[ 0.00631846 -0.22182073  0.07327189  0.33213979]


[0.07081197 0.67793046 0.16835419 0.09835425]
[0.08437058 0.48084589 0.17032127 0.43906414]
[0.0939875  0.28377441 0.17910255 0.78022674]
[0.09966299 0.08670188 0.19470709 1.12348205]
[ 0.03247269  0.04235948  0.01443819 -0.01143461]
[ 0.03331988 -0.15296653  0.01420949  0.28576854]
[ 0.03026055 -0.34828822  0.01992487  0.58289895]
[ 0.02329479 -0.153451    0.03158284  0.29655865]
[0.02022577 0.04120682 0.03751402 0.01400135]
[ 0.0210499   0.23577125  0.03779404 -0.26661342]
[0.02576533 0.04013085 0.03246178 0.03774641]
[ 0.02656795 -0.15544121  0.0332167   0.34049203]
[0.02345912 0.03919277 0.04002654 0.05846603]
[ 0.02424298 -0.15647955  0.04119587  0.36350408]
[ 0.02111339 -0.35216205  0.04846595  0.66888695]
[ 0.01407014 -0.15774632  0.06184369  0.39184922]
[0.01091522 0.03644594 0.06968067 0.11928813]
[ 0.01164414  0.23050394  0.07206643 -0.15062293]
[ 0.01625422  0.42452392  0.06905397 -0.41972829]
[ 0.02474469  0.61860293  0.06065941 -0.68986725]
[ 0.03711675  0.42269399  0.0468

[-0.08404688  0.34210013  0.09414046 -0.34942427]
[-0.07720488  0.53576591  0.08715197 -0.6110002 ]
[-0.06648956  0.33954088  0.07493197 -0.2921895 ]
[-0.05969874  0.5335189   0.06908818 -0.56033067]
[-0.04902837  0.33749877  0.05788156 -0.24670616]
[-0.04227839  0.14159997  0.05294744  0.06365762]
[-0.03944639  0.33592438  0.05422059 -0.21186123]
[-0.0327279   0.53023087  0.04998337 -0.4869596 ]
[-0.02212329  0.3344406   0.04024417 -0.17895199]
[-0.01543447  0.52896423  0.03666514 -0.45867258]
[-0.00485519  0.33334368  0.02749168 -0.15466183]
[0.00181168 0.1378391  0.02439845 0.14656575]
[ 0.00456847 -0.05762359  0.02732976  0.44684497]
[ 0.00341599 -0.25312129  0.03626666  0.74801596]
[-0.00164643 -0.4487243   0.05122698  1.05188759]
[-0.01062092 -0.25431775  0.07226473  0.77571446]
[-0.01570727 -0.06026022  0.08777902  0.50661522]
[-0.01691248  0.13352229  0.09791133  0.24283449]
[-0.01424203 -0.06285196  0.10276802  0.56472503]
[-0.01549907  0.13068938  0.11406252  0.30610534]
[-0.

[ 0.03823652  0.04884405 -0.00492815 -0.00813872]
[ 0.0392134  -0.14620688 -0.00509092  0.28298525]
[ 3.62892640e-02 -3.41255850e-01  5.68782630e-04  5.74058191e-01]
[ 0.02946415 -0.14614188  0.01204995  0.2815545 ]
[ 0.02654131  0.04880614  0.01768104 -0.00730369]
[ 0.02751743  0.24367011  0.01753496 -0.29435602]
[ 0.03239083  0.43853774  0.01164784 -0.5814575 ]
[ 4.11615892e-02  2.43254535e-01  1.86923306e-05 -2.85128178e-01]
[ 0.04602668  0.04813232 -0.00568387  0.00756064]
[ 0.04698933  0.24333532 -0.00553266 -0.28691018]
[ 0.05185603  0.43853573 -0.01127086 -0.58133291]
[ 0.06062675  0.63381378 -0.02289752 -0.87754494]
[ 0.07330302  0.43901037 -0.04044842 -0.59214771]
[ 0.08208323  0.24447732 -0.05229137 -0.31247539]
[ 0.08697278  0.44030371 -0.05854088 -0.62118014]
[ 0.09577885  0.24604604 -0.07096448 -0.34749397]
[ 0.10069977  0.44210184 -0.07791436 -0.66168353]
[ 0.10954181  0.24814551 -0.09114803 -0.39451532]
[ 0.11450472  0.05442714 -0.09903834 -0.13190442]
[ 0.11559326  0.25

[ 0.05204919  0.4522392  -0.14055567 -0.90119995]
[ 0.06109398  0.25927269 -0.15857967 -0.65579208]
[ 0.06627943  0.06667224 -0.17169551 -0.41694364]
[ 0.06761287 -0.12565364 -0.18003439 -0.18292745]
[ 0.0650998  -0.3178041  -0.18369294  0.04799517]
[ 0.05874372 -0.12058847 -0.18273303 -0.29655381]
[ 0.05633195  0.07660414 -0.18866411 -0.64084308]
[ 0.05786403 -0.11545668 -0.20148097 -0.41300263]
[-0.0479618  -0.03973864 -0.04920241 -0.02342192]
[-0.04875657  0.15605312 -0.04967085 -0.33121383]
[-0.04563551 -0.0383279  -0.05629512 -0.05459913]
[-0.04640207  0.15755417 -0.05738711 -0.36449879]
[-0.04325099 -0.03670725 -0.06467708 -0.0904489 ]
[-0.04398513 -0.2308454  -0.06648606  0.18114765]
[-0.04860204 -0.03483818 -0.06286311 -0.1317461 ]
[-0.0492988  -0.22900595 -0.06549803  0.14046067]
[-0.05387892 -0.42313166 -0.06268882  0.41178221]
[-0.06234155 -0.61731151 -0.05445317  0.68406141]
[-0.07468778 -0.42147746 -0.04077194  0.3747444 ]
[-0.08311733 -0.61599726 -0.03327706  0.654298  ]


[-0.03100542  0.23593468  0.0487939  -0.2517321 ]
[-0.02628672  0.04015116  0.04375926  0.05593337]
[-0.0254837   0.23461924  0.04487793 -0.22262839]
[-0.02079132  0.03888553  0.04042536  0.08386624]
[-0.02001361  0.23340539  0.04210269 -0.19579334]
[-0.0153455   0.03770728  0.03818682  0.10986822]
[-0.01459135  0.23226181  0.04038418 -0.17052662]
[-0.00994612  0.42678317  0.03697365 -0.45020104]
[-0.00141045  0.6213632   0.02796963 -0.73100383]
[ 0.01101681  0.81608767  0.01334955 -1.0147543 ]
[ 0.02733856  0.62079025 -0.00694553 -0.71790961]
[ 0.03975437  0.4257651  -0.02130372 -0.42742091]
[ 0.04826967  0.23095125 -0.02985214 -0.14152927]
[ 0.0528887   0.03626928 -0.03268273  0.14158835]
[ 0.05361408  0.23184369 -0.02985096 -0.16122362]
[ 0.05825096  0.03716153 -0.03307543  0.12189465]
[ 0.05899419  0.23274135 -0.03063754 -0.18103703]
[ 0.06364901  0.0380709  -0.03425828  0.10182558]
[ 0.06441043  0.23366664 -0.03222177 -0.20146585]
[ 0.06908376  0.42923426 -0.03625109 -0.50413655]


[ 0.01482107 -0.04413115 -0.02542402 -0.02471157]
[ 0.01393844 -0.23887945 -0.02591826  0.25984261]
[ 0.00916085 -0.04339727 -0.0207214  -0.04090129]
[ 0.00829291 -0.23821604 -0.02153943  0.24517248]
[ 0.00352859 -0.04279318 -0.01663598 -0.05422593]
[ 0.00267272  0.15256331 -0.0177205  -0.35211086]
[ 0.00572399 -0.04230222 -0.02476272 -0.06506801]
[ 0.00487795 -0.23706055 -0.02606408  0.21970043]
[ 0.00013673 -0.04157591 -0.02167007 -0.08108891]
[-0.00069478 -0.23638063 -0.02329185  0.20467906]
[-0.0054224  -0.43116188 -0.01919826  0.48992451]
[-0.01404563 -0.23577443 -0.00939977  0.1912534 ]
[-0.01876112 -0.04051928 -0.00557471 -0.10437988]
[-0.01957151 -0.2355609  -0.0076623   0.18653904]
[-0.02428273 -0.04033016 -0.00393152 -0.10855116]
[-0.02508933 -0.23539555 -0.00610255  0.1828888 ]
[-0.02979724 -0.43042966 -0.00244477  0.47364037]
[-0.03840583 -0.23527326  0.00702804  0.18018789]
[-0.0431113  -0.04025258  0.0106318  -0.11026968]
[-0.04391635  0.15471542  0.0084264  -0.39957946]


KeyboardInterrupt: 